version: '3'

services:
  go-app:
    build: .
    volumes:
      - .:/app # 現在のディレクトリをコンテナの/appにマウント
    tty: true
    
  db:
    image: postgres:17.2
    container_name: postgres_container
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: simulatio-manage
    restart: always

volumes:
  postgres_data: