# Go言語のイメージをベースにする
FROM golang:1.23.6-alpine3.20 AS builder

# 作業ディレクトリの設定
WORKDIR /app

# 依存関係を解決するためのgo.mod, go.sumをコピー
COPY go.mod go.sum ./

# 依存関係をダウンロード
RUN go mod tidy

# ソースコードをコピー
COPY . .

# アプリケーションをビルド
RUN go build -o main .

# 実行専用コンテナ
FROM alpine:3.20
WORKDIR /app

# ビルド済みバイナリをコピー
COPY --from=builder /app/main .

# コンテナ起動時にバイナリを実行
CMD ["./main"]